/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogopalavra.interfaces;

import jogopalavra.arquivo.*;
import jogopalavra.modelo.Tema;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Herlen
 */
public class tela2 extends javax.swing.JDialog {

    /**
     * Creates new form tela2
     */
    Jogador jogadores = new Jogador();
    Arquivos arq = new Arquivos();
    PalavrasTemas sorteadorDeTemas = new PalavrasTemas();
    int moeda = 50;
    int cont = 0;
    int numJogador = 0;
    int nivelAtual = 1;
    Tema tema;
    String cursoAluno;
    String jogador;
    String tipoJogador;

    public tela2(java.awt.Frame parent, boolean modal, Tema tema, String jogador, String curso, String tipoJogador) {

        super(parent, modal);
        initComponents();

        btAdquirirMoeda.setVisible(false);
        pfSenha.setVisible(false);
        lbSenha.setVisible(false);
        cbxMoedas.setVisible(false);

        cbxMoedas.removeAllItems();

        cbxMoedas.addItem(50);
        cbxMoedas.addItem(75);
        cbxMoedas.addItem(100);

        this.getContentPane().setBackground(new Color(255, 255, 255));
        this.setLocationRelativeTo(null);

        jogadores.teste((cont + 1) + "");
        lbNumJogador.setText(jogadores.lerTextoArquivo());
        
        this.tipoJogador = tipoJogador;
        this.tema = tema;
        this.cursoAluno = curso;
        this.jogador = jogador;
        //arq.teste("Nome: " + jogador + "\tCurso: " + tema.getTema() + "\tTotal de Moedas : " + moeda+"\n");

        lbNivel.setText("1");
        lbNaoEncontrada.setVisible(false);
        lbBoasVindas.setText("Bem vindo, " + jogador);
        tema.setNomeJogador(jogador);
        lbMoeda.setText(moeda + "");

        // Preenchendo tema inicial
        preencherCampos(tema);

        // variaveis de cores;
        tfTema.setBackground(new Color((int) (Math.random() * 255), (int) (Math.random() * 255), (int) (Math.random() * 255)));
        lbNivel.setForeground(Color.BLUE);

    }

    public void preencherCampos(Tema tema) {
        tfTema.setText(tema.getTema());

        lbPorcentagem1.setText(tema.getPorcentagem1() + "%");
        lbPorcentagem2.setText(tema.getPorcentagem2() + "%");
        lbPorcentagem3.setText(tema.getPorcentagem3() + "%");
        lbPorcentagem4.setText(tema.getPorcentagem4() + "%");
        lbPorcentagem5.setText(tema.getPorcentagem5() + "%");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNumJogador = new javax.swing.JTextField();
        lbBoasVindas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTema = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lbMoeda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        afda = new javax.swing.JLabel();
        lbNivel = new javax.swing.JLabel();
        pnNivel1 = new javax.swing.JPanel();
        pn1 = new javax.swing.JPanel();
        lbPorcentagem1 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        lbPorcentagem2 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        lbPorcentagem3 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        lbPorcentagem4 = new javax.swing.JLabel();
        pn5 = new javax.swing.JPanel();
        lbPorcentagem5 = new javax.swing.JLabel();
        tfResultadoPesquisa = new javax.swing.JTextField();
        btOK = new javax.swing.JButton();
        lbresp1 = new javax.swing.JLabel();
        lbresp2 = new javax.swing.JLabel();
        lbresp3 = new javax.swing.JLabel();
        lbresp4 = new javax.swing.JLabel();
        lbresp5 = new javax.swing.JLabel();
        btComprar1 = new javax.swing.JButton();
        btComprar2 = new javax.swing.JButton();
        btComprar3 = new javax.swing.JButton();
        btComprar4 = new javax.swing.JButton();
        btComprar5 = new javax.swing.JButton();
        lbNaoEncontrada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btAdquirirMoeda = new javax.swing.JButton();
        pfSenha = new javax.swing.JPasswordField();
        lbSenha = new javax.swing.JLabel();
        cbxMoedas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Jogo");

        jLabel1.setText("Jogador N°:");

        lbNumJogador.setEnabled(false);

        lbBoasVindas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbBoasVindas.setForeground(new java.awt.Color(0, 0, 255));
        lbBoasVindas.setText("Bem - Vindo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seu Tema é:");

        tfTema.setEditable(false);
        tfTema.setBackground(new java.awt.Color(255, 0, 204));
        tfTema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTema.setForeground(new java.awt.Color(255, 255, 255));
        tfTema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTema.setText("Informatica");
        tfTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTemaActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbMoeda.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lbMoeda.setForeground(new java.awt.Color(0, 0, 255));
        lbMoeda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMoeda.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Moedas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Você tem:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lbMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lbMoeda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        afda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        afda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afda.setText("Nivel:");

        lbNivel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNivel.setText(" ");

        pnNivel1.setBackground(new java.awt.Color(255, 255, 255));
        pnNivel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pn1.setBackground(new java.awt.Color(0, 255, 255));
        pn1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPorcentagem1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        lbPorcentagem1.setForeground(new java.awt.Color(0, 51, 255));
        lbPorcentagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPorcentagem1.setText("25%");

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn2.setBackground(new java.awt.Color(0, 255, 255));
        pn2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPorcentagem2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        lbPorcentagem2.setForeground(new java.awt.Color(0, 51, 255));
        lbPorcentagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPorcentagem2.setText("15%");

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn3.setBackground(new java.awt.Color(0, 255, 255));
        pn3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPorcentagem3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        lbPorcentagem3.setForeground(new java.awt.Color(0, 0, 255));
        lbPorcentagem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPorcentagem3.setText("12%");

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn3Layout.setVerticalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn4.setBackground(new java.awt.Color(0, 255, 255));
        pn4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPorcentagem4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        lbPorcentagem4.setForeground(new java.awt.Color(0, 0, 255));
        lbPorcentagem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPorcentagem4.setText("7%");

        javax.swing.GroupLayout pn4Layout = new javax.swing.GroupLayout(pn4);
        pn4.setLayout(pn4Layout);
        pn4Layout.setHorizontalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn4Layout.setVerticalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn5.setBackground(new java.awt.Color(0, 255, 255));
        pn5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbPorcentagem5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        lbPorcentagem5.setForeground(new java.awt.Color(0, 0, 255));
        lbPorcentagem5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPorcentagem5.setText("5%");

        javax.swing.GroupLayout pn5Layout = new javax.swing.GroupLayout(pn5);
        pn5.setLayout(pn5Layout);
        pn5Layout.setHorizontalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn5Layout.setVerticalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPorcentagem5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfResultadoPesquisa.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        tfResultadoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfResultadoPesquisaKeyPressed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        lbresp1.setBackground(new java.awt.Color(255, 255, 255));
        lbresp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbresp1.setForeground(new java.awt.Color(0, 0, 204));
        lbresp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbresp2.setBackground(new java.awt.Color(255, 255, 255));
        lbresp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbresp2.setForeground(new java.awt.Color(0, 0, 204));
        lbresp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbresp3.setBackground(new java.awt.Color(204, 204, 204));
        lbresp3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbresp3.setForeground(new java.awt.Color(0, 0, 204));
        lbresp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbresp4.setBackground(new java.awt.Color(255, 255, 255));
        lbresp4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbresp4.setForeground(new java.awt.Color(0, 0, 204));
        lbresp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbresp5.setBackground(new java.awt.Color(255, 255, 255));
        lbresp5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbresp5.setForeground(new java.awt.Color(0, 0, 204));
        lbresp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btComprar1.setText("Comprar");
        btComprar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprar1ActionPerformed(evt);
            }
        });

        btComprar2.setText("Comprar");
        btComprar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprar2ActionPerformed(evt);
            }
        });

        btComprar3.setText("Comprar");
        btComprar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprar3ActionPerformed(evt);
            }
        });

        btComprar4.setText("Comprar");
        btComprar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprar4ActionPerformed(evt);
            }
        });

        btComprar5.setText("Comprar");
        btComprar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprar5ActionPerformed(evt);
            }
        });

        lbNaoEncontrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNaoEncontrada.setForeground(new java.awt.Color(255, 0, 0));
        lbNaoEncontrada.setText("Palavra não encontrada");

        jLabel2.setText("Digite a palavra:");

        javax.swing.GroupLayout pnNivel1Layout = new javax.swing.GroupLayout(pnNivel1);
        pnNivel1.setLayout(pnNivel1Layout);
        pnNivel1Layout.setHorizontalGroup(
            pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNivel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnNivel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfResultadoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNivel1Layout.createSequentialGroup()
                        .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnNivel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btComprar1))
                            .addComponent(lbresp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNivel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbresp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnNivel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btComprar2)))
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNivel1Layout.createSequentialGroup()
                                .addComponent(btComprar3)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNivel1Layout.createSequentialGroup()
                                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbresp3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNivel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btComprar4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNivel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbresp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNivel1Layout.createSequentialGroup()
                        .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNivel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbresp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNivel1Layout.createSequentialGroup()
                        .addComponent(btComprar5)
                        .addGap(26, 26, 26))))
            .addGroup(pnNivel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lbNaoEncontrada)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnNivel1Layout.setVerticalGroup(
            pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNivel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbresp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lbresp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbresp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbresp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbresp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btComprar2)
                    .addComponent(btComprar1)
                    .addComponent(btComprar3)
                    .addComponent(btComprar4)
                    .addComponent(btComprar5))
                .addGap(39, 39, 39)
                .addGroup(pnNivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfResultadoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNaoEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btAdquirirMoeda.setText("Adquirir Moeda");
        btAdquirirMoeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdquirirMoedaActionPerformed(evt);
            }
        });

        lbSenha.setText("Senha:");

        cbxMoedas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfTema, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnNivel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(afda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(lbSenha)
                                        .addGap(128, 128, 128)
                                        .addComponent(cbxMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btAdquirirMoeda)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNumJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lbBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNumJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfTema, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdquirirMoeda)
                            .addComponent(lbSenha)
                            .addComponent(cbxMoedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnNivel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTemaActionPerformed

    private void btComprar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprar1ActionPerformed
        comprarPalavra(1);
    }//GEN-LAST:event_btComprar1ActionPerformed

    private void btComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprar2ActionPerformed
        comprarPalavra(2);
    }//GEN-LAST:event_btComprar2ActionPerformed

    private void btComprar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprar3ActionPerformed
        comprarPalavra(3);
    }//GEN-LAST:event_btComprar3ActionPerformed

    private void btComprar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprar4ActionPerformed
        comprarPalavra(4);
    }//GEN-LAST:event_btComprar4ActionPerformed

    private void btComprar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprar5ActionPerformed
        comprarPalavra(5);
    }//GEN-LAST:event_btComprar5ActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        verificarPalavra();
    }//GEN-LAST:event_btOKActionPerformed

    private void tfResultadoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfResultadoPesquisaKeyPressed

        if (evt.getKeyCode() == 10) {
            if (tfResultadoPesquisa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, digite uma palavra!", "Ops!", 0);
            } else {
                verificarPalavra();
            }

        }
    }//GEN-LAST:event_tfResultadoPesquisaKeyPressed

    private void btAdquirirMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdquirirMoedaActionPerformed
        String senha = "15429";
        if (pfSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "digite a Senha!", "Ops!", 0);
        } else {
            if (pfSenha.getText().equalsIgnoreCase(senha)) {
                if (cbxMoedas.getSelectedIndex() == 0) {
                    moeda = moeda + 50;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "Comprada com sucesso!", "Ops!", 0);
                    btAdquirirMoeda.setVisible(false);
                    pfSenha.setVisible(false);
                    lbSenha.setVisible(false);
                    cbxMoedas.setVisible(false);
                }
                if (cbxMoedas.getSelectedIndex() == 1) {
                    moeda = moeda + 70;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "Comprada com sucesso!", "Ops!", 0);
                    btAdquirirMoeda.setVisible(false);
                    pfSenha.setVisible(false);
                    lbSenha.setVisible(false);
                    cbxMoedas.setVisible(false);
                }
                if (cbxMoedas.getSelectedIndex() == 2) {
                    moeda = moeda + 100;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "Comprada com sucesso!", "Ops!", 0);
                    btAdquirirMoeda.setVisible(false);
                    pfSenha.setVisible(false);
                    lbSenha.setVisible(false);
                    cbxMoedas.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha errada!", "Ops!", 0);
            }
        }


    }//GEN-LAST:event_btAdquirirMoedaActionPerformed

    /**
     * Verifica SE a palavra digitada pelo usuário é uma das palavras sorteadas
     * do Tema.
     */
    private void verificarPalavra() {

        if (tfResultadoPesquisa.getText().equals("15429a")) {
            btAdquirirMoeda.setVisible(true);
            pfSenha.setVisible(true);
            lbSenha.setVisible(true);
            cbxMoedas.setVisible(true);
        }
        if (tfResultadoPesquisa.getText().toUpperCase().equals(tema.getPalavra1().toUpperCase())) {

            if (!lbresp1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Palavra já encontrada!", "Ops!", 0);
                tfResultadoPesquisa.setText("");
            } else {
                moeda = moeda + 2;
                lbMoeda.setText(moeda + "");
                lbresp1.setText(tema.getPalavra1());
                btComprar1.setEnabled(false);
                System.out.println("correto num 1");
                tfResultadoPesquisa.setText("");
                lbNaoEncontrada.setVisible(false);
                cont = cont + 1;

                if (cont == 5) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 10) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 15) {
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                    arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                    this.dispose();
                }
            }
        } else if (tfResultadoPesquisa.getText().toUpperCase().equals(tema.getPalavra2().toUpperCase())) {

            if (!lbresp2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Palavra já encontrada!", "Ops!", 0);
                tfResultadoPesquisa.setText("");
            } else {
                moeda = moeda + 2;
                lbMoeda.setText(moeda + "");
                lbresp2.setText("<html>" + tema.getPalavra2() + "</html>");
                System.out.println("correto num 2");
                tfResultadoPesquisa.setText("");
                lbNaoEncontrada.setVisible(false);
                btComprar2.setEnabled(false);
                cont = cont + 1;

                if (cont == 5) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 10) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 15) {
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                    arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                    this.dispose();
                }
            }
        } else if (tfResultadoPesquisa.getText().toUpperCase().equals(tema.getPalavra3().toUpperCase())) {

            if (!lbresp3.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Palavra já encontrada!", "Ops!", 0);
                tfResultadoPesquisa.setText("");
            } else {
                moeda = moeda + 2;
                lbMoeda.setText(moeda + "");
                lbresp3.setText("<html>" + tema.getPalavra3() + "</html>");
                System.out.println("correto num 3");
                tfResultadoPesquisa.setText("");
                lbNaoEncontrada.setVisible(false);
                btComprar3.setEnabled(false);
                cont = cont + 1;

                if (cont == 5) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 10) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 15) {
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                    arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                    this.dispose();
                }
            }
        } else if (tfResultadoPesquisa.getText().toUpperCase().equals(tema.getPalavra4().toUpperCase())) {

            if (!lbresp4.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Palavra já encontrada!", "Ops!", 0);
                tfResultadoPesquisa.setText("");
            } else {
                moeda = moeda + 2;
                lbMoeda.setText(moeda + "");
                lbresp4.setText("<html>" + tema.getPalavra4() + "</html>");
                btComprar4.setEnabled(false);
                System.out.println("correto num 4");
                tfResultadoPesquisa.setText("");
                lbNaoEncontrada.setVisible(false);
                cont = cont + 1;

                if (cont == 5) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 10) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 15) {
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                    arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                    this.dispose();
                    
                }
            }
        } else if (tfResultadoPesquisa.getText().toUpperCase().equals(tema.getPalavra5().toUpperCase())) {

            if (!lbresp5.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Palavra já encontrada!", "Ops!", 0);
                tfResultadoPesquisa.setText("");
            } else {
                moeda = moeda + 2;
                lbMoeda.setText(moeda + "");
                lbresp5.setText("<html>" + tema.getPalavra5() + "</html>");
                System.out.println("correto num 5");
                tfResultadoPesquisa.setText("");
                lbNaoEncontrada.setVisible(false);
                btComprar5.setEnabled(false);
                cont = cont + 1;

                if (cont == 5) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 10) {
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabens,você passou de nivel!!<br> Ganhou <font color='blue'>10</font> Moedas</html>");
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    novonivel();
                }
                if (cont == 15) {
                    moeda = moeda + 10;
                    lbMoeda.setText(moeda + "");
                    JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                    arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                    this.dispose();
                }
            }
        } else {
            lbNaoEncontrada.setVisible(true);
            tfResultadoPesquisa.setText("");
            //moeda = moeda - 2;
           // lbMoeda.setText(moeda + "");
        }

    }

    private void comprarPalavra(int numeroBotao) {
        int resp = JOptionPane.showConfirmDialog(null, "<html><h3>Realmente deseja comprar a palavra?<br>Irá lhe custar<font color='red' size = 18> -5 moedas!</font></html>", "Comprar palavra?", 0, 0);

        if (resp == 0) {
            switch (numeroBotao) {
                case 1:
                    lbresp1.setText(tema.getPalavra1());
                    btComprar1.setEnabled(false);
                    break;

                case 2:
                    lbresp2.setText(tema.getPalavra2());
                    btComprar2.setEnabled(false);
                    break;

                case 3:
                    lbresp3.setText(tema.getPalavra3());
                    btComprar3.setEnabled(false);
                    break;

                case 4:
                    lbresp4.setText(tema.getPalavra4());
                    btComprar4.setEnabled(false);
                    break;

                case 5:
                    lbresp5.setText(tema.getPalavra5());
                    btComprar5.setEnabled(false);
                    break;
            }

            moeda = moeda - 5;
            lbMoeda.setText(moeda + "");
            cont = cont + 1;
            if (cont == 5) // passando pro nivel 2
            {
                moeda = moeda + 10;
                lbMoeda.setText(moeda + "");
                JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você passou de nível!!<br> Ganhou <font color=blue size= 13>10</font> Moedas</html>");
                novonivel();

            }

            if (cont == 10) // passando pro nivel 3
            {
                moeda = moeda + 10;
                lbMoeda.setText(moeda + "");
                JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você passou de nível!!<br> Ganhou <font color=blue size= 13>10</font> Moedas</html>");
                novonivel();
            }
            if (cont == 15) {
                moeda = moeda + 10;
                lbMoeda.setText(moeda + "");
                JOptionPane.showMessageDialog(null, "<html><h3>Parabéns,você COMPLETOoOoU!!<br> Restou <font color='blue' size= 13>" + moeda + "</font> Moedas<br> Vá trocar suas moedas por um prêmio</html>");
                arq.teste("Jogador N°.:  " + jogadores.lerTextoArquivo() + "\t // Nome: " + jogador + "\t // Status: " + tipoJogador + "\t // Moedas: " + moeda);

                this.dispose();
            }
        }

    }

    private void novonivel() {
        if (cont == 5) // passando pro nivel 2
        {
            lbNivel.setText("2");
            lbresp1.setText("");
            lbresp2.setText("");
            lbresp3.setText("");
            lbresp4.setText("");
            lbresp5.setText("");

            btComprar1.setEnabled(true);
            btComprar2.setEnabled(true);
            btComprar3.setEnabled(true);
            btComprar4.setEnabled(true);
            btComprar5.setEnabled(true);

            pn1.setBackground(Color.yellow);
            pn2.setBackground(Color.yellow);
            pn3.setBackground(Color.yellow);
            pn4.setBackground(Color.yellow);
            pn5.setBackground(Color.yellow);

            tfTema.setBackground(Color.ORANGE);
            lbNivel.setForeground(Color.yellow);
            iniciarNovoNivel();
            preencherCampos(tema);
        }

        if (cont == 10) // passando pro nivel 3
        {
            lbNivel.setText("3");

            lbresp1.setText("");
            lbresp2.setText("");
            lbresp3.setText("");
            lbresp4.setText("");
            lbresp5.setText("");

            btComprar1.setEnabled(true);
            btComprar2.setEnabled(true);
            btComprar3.setEnabled(true);
            btComprar4.setEnabled(true);
            btComprar5.setEnabled(true);

            lbPorcentagem1.setForeground(Color.white);
            lbPorcentagem2.setForeground(Color.white);
            lbPorcentagem3.setForeground(Color.white);
            lbPorcentagem4.setForeground(Color.white);
            lbPorcentagem5.setForeground(Color.white);

            pn1.setBackground(Color.red);
            pn2.setBackground(Color.red);
            pn3.setBackground(Color.red);
            pn4.setBackground(Color.red);
            pn5.setBackground(Color.red);

            tfTema.setBackground(Color.RED);
            lbNivel.setForeground(Color.RED);
            iniciarNovoNivel();
            preencherCampos(tema);
        }
    }

    private void iniciarNovoNivel() {
        nivelAtual++; // Aumentando um nível
        tema = sorteadorDeTemas.retornarNovoTema(nivelAtual, cursoAluno, 1);
        System.out.println(cont);
        preencherCampos(tema);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tela2 dialog = new tela2(new javax.swing.JFrame(), true, null, "", "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afda;
    private javax.swing.JButton btAdquirirMoeda;
    private javax.swing.JButton btComprar1;
    private javax.swing.JButton btComprar2;
    private javax.swing.JButton btComprar3;
    private javax.swing.JButton btComprar4;
    private javax.swing.JButton btComprar5;
    private javax.swing.JButton btOK;
    private javax.swing.JComboBox cbxMoedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbBoasVindas;
    private javax.swing.JLabel lbMoeda;
    private javax.swing.JLabel lbNaoEncontrada;
    private javax.swing.JLabel lbNivel;
    private javax.swing.JTextField lbNumJogador;
    private javax.swing.JLabel lbPorcentagem1;
    private javax.swing.JLabel lbPorcentagem2;
    private javax.swing.JLabel lbPorcentagem3;
    private javax.swing.JLabel lbPorcentagem4;
    private javax.swing.JLabel lbPorcentagem5;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbresp1;
    private javax.swing.JLabel lbresp2;
    private javax.swing.JLabel lbresp3;
    private javax.swing.JLabel lbresp4;
    private javax.swing.JLabel lbresp5;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JPanel pn5;
    private javax.swing.JPanel pnNivel1;
    private javax.swing.JTextField tfResultadoPesquisa;
    private javax.swing.JTextField tfTema;
    // End of variables declaration//GEN-END:variables
}
